<?php 
/**
	Admin Page Framework v3.8.13 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/presscode>
	Copyright (c) 2013-2016, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class Pcode_AdminPageFramework_Form_View___CSS_term_meta extends Pcode_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".presscode-form-table-outer-row-term_meta,.presscode-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.presscode-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.presscode-form-table-term_meta .presscode-sectionset,.presscode-form-table-term_meta .presscode-section {margin-bottom: 0;}.presscode-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.presscode-form-table-term_meta.add-new-term .presscode-section .form-table > tbody > tr > td,.presscode-form-table-term_meta.add-new-term .presscode-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.presscode-form-table-term_meta.add-new-term .presscode-field {width: auto;}.presscode-form-table-term_meta.add-new-term .presscode-field {max-width: 100%;}.presscode-form-table-term_meta.add-new-term .sortable .presscode-field {width: auto;} .presscode-form-table-term_meta.add-new-term .presscode-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.presscode-form-table-term_meta .presscode-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.presscode-form-table-term_meta .presscode-collapsible-title h3 {margin: 0;}.presscode-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.presscode-form-table-term_meta .presscode-section-tab h4 {margin: 0;} ";
    }
}
