package com.vincent.entity;

public class Options {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.id
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.topic_id
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.content
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column options.votes
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    private Integer votes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.id
     *
     * @return the value of options.id
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.id
     *
     * @param id the value for options.id
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.topic_id
     *
     * @return the value of options.topic_id
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.topic_id
     *
     * @param topicId the value for options.topic_id
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.content
     *
     * @return the value of options.content
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.content
     *
     * @param content the value for options.content
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column options.votes
     *
     * @return the value of options.votes
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    public Integer getVotes() {
        return votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column options.votes
     *
     * @param votes the value for options.votes
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    public void setVotes(Integer votes) {
        this.votes = votes;
    }
}