package com.vincent.entity;

import java.util.Date;

public class Survey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.id
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.topic
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.mode
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    private String mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.create_time
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey.end_time
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.id
     *
     * @return the value of survey.id
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.id
     *
     * @param id the value for survey.id
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.topic
     *
     * @return the value of survey.topic
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.topic
     *
     * @param topic the value for survey.topic
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.mode
     *
     * @return the value of survey.mode
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.mode
     *
     * @param mode the value for survey.mode
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.create_time
     *
     * @return the value of survey.create_time
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.create_time
     *
     * @param createTime the value for survey.create_time
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey.end_time
     *
     * @return the value of survey.end_time
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey.end_time
     *
     * @param endTime the value for survey.end_time
     *
     * @mbggenerated Thu Jan 12 21:41:36 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}