package com.vincent.dao.mapper;

import com.vincent.entity.Options;
import com.vincent.entity.OptionsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    int countByExample(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    int deleteByExample(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    int insert(Options record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    int insertSelective(Options record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    List<Options> selectByExample(OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    Options selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") Options record, @Param("example") OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    int updateByExample(@Param("record") Options record, @Param("example") OptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    int updateByPrimaryKeySelective(Options record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbggenerated Thu Jan 12 21:44:46 CST 2017
     */
    int updateByPrimaryKey(Options record);
}